version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: oracle/database:19.3.0-ee
    environment:
      - ORACLE_PWD=080297
    ports:
      - "1521:1521"
