apiVersion: v1
kind: Service
metadata:
  name: app-service-production
  namespace: production
spec:
  selector:
    app: app-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer