apiVersion: v1
kind: Service
metadata:
  name: app-service-staging
  namespace: staging
spec:
  selector:
    app: app-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer